//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace שרת_שנה_ג.ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Corona_DBEntities : DbContext
    {
        public Corona_DBEntities()
            : base("name=Corona_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City_tb> City_tb { get; set; }
        public DbSet<Image_tb> Image_tb { get; set; }
        public DbSet<manufacturerVaccine_tb> manufacturerVaccine_tb { get; set; }
        public DbSet<Street_tb> Street_tb { get; set; }
        public DbSet<CoronaDetails_tb> CoronaDetails_tb { get; set; }
        public DbSet<Person_tb> Person_tb { get; set; }
    }
}
