//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace שרת_שנה_ג.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoronaDetails_tb
    {
        public int CoronaDetailsId { get; set; }
        public string PersonId { get; set; }
        public Nullable<System.DateTime> vaccinationDate1 { get; set; }
        public Nullable<System.DateTime> vaccinationDate2 { get; set; }
        public Nullable<System.DateTime> vaccinationDate3 { get; set; }
        public Nullable<System.DateTime> vaccinationDate4 { get; set; }
        public Nullable<int> manufacturerVaccineId { get; set; }
        public Nullable<System.DateTime> positiveResultDate { get; set; }
        public Nullable<System.DateTime> recoveryDate { get; set; }
    
        public virtual manufacturerVaccine_tb manufacturerVaccine_tb { get; set; }
        public virtual Person_tb Person_tb { get; set; }
    }
}
